### ISSUE TITLE
getProfileCharacters are missing

### ISSUE THREAD

**Issue by atraides** [xklusive/laravel-battlenet-api#17]
It was really hard to test this function so I removed it from the final version. However it would be good to have it back.

Maybe with some tests :)

**Comment by xklusive** [comment]
Of course this method is really hard to test because we need a valid access token from oauth process.

Anyway i added it back because maybe some projects were using it. 

I created a test that assert it failed, but we should write a test that assert it passed, but i don't know how we could do that.
Any idea ?

**Comment by atraides** [comment]
I think the test suite should be remade entirely. At the moment we are connecting a third party service with every single request. This is problematic, because what happens if Blizzard API is not available for some reason? In this case our test will fail even though the code works exactly as it should.

Before I went for a longer hiatus I checked the possibility to test queries using a fake connection with the HTTP library. maybe push it to the next version.

For now the functionality is back so this can be closed.
